---
version: '3.9'

services:
  postgres:
    container_name: arc-postgres
    image: postgres:12-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - .docker:/docker-entrypoint-initdb.d
  adminer:
    container_name: arc-adminer
    image: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080
  app:
    container_name: arc-app
    image: acim/go-reflex
    depends_on:
      - postgres
    environment:
      - RACE_DETECTOR=1
      - JWT_SECRET=emUhG5q10P3aRWEu5k3LCiQPcVD6VZ2zTvNFm4BrWfTC0gzZF1nXDC3ts21j50V
      - MG_DOMAIN
      - MG_API_KEY
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 3001:3001
volumes:
  postgres:
